name: Linux x64 Build
on:
  push:
    branches: [ "gh-build" ]
  pull_request:
    branches: [ "gh-build" ]

jobs:
  x64-linux-build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile chsrc x64
      run: |
        make CI CI_Build_Name=chsrc-x64-linux

    - name: List files
      run: ls *-linux

    - name: Release
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: pre
        files: |
          chsrc-x64-linux
        token: ${{ secrets.CHSRC_UPLOAD }}
